import type { Metadata } from "next";
import localFont from "next/font/local";
import Navbar from "./ui/navbar";
import "./globals.css";
import Footer from "./ui/Footer";
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Navbar />
        <div className="flex bg-black/95 backdrop-blur-sm">
          <div className="flex-1 min-h-[88vh]">{children}</div>
        </div>
        <Footer />
      </body>
    </html>
  );
}
